@ -1,10 +1,9 @@
# config
logo: /images/logo.png
keywords: "pen, notes, coding, developer, mkkhedawat, manish kumar khedawat, javascript, c++, nodejs, angularjs"
menu:
  home: /
  articles: /articles
  author: /author
  home: ' '
  articles: articles
  author: author

# Content
excerpt_link: Read more
